version: '3.7'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=project/__init__.py
      - DATABASE_URL=postgres://jigsawlabs:secret@db:5432/jigsawlabs
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jigsawlabs
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data:


